source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "rake", "~> 12.3.3"
gem "html-proofer"
# 구글 seo 플러그"
gem "jekyll-seo-tag"
gem "rexml"
gem "webrick"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-gist"
gem "kramdown-parser-gfm"
